import folium

# --- Map Configuration and Constants ---

# Replaced the original problematic URL with Stadia Maps Alidade Smooth Dark, a stable, free tile provider.
CLASSIFIED_MAP_TILE_URL = "https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png"

# Initial central coordinates (approximate center of the Maasai Mara ecosystem)
lat, lon = -1.45, 35.0

# Define a dictionary of reliable, free basemaps.
# Authentication-prone ESRI or Stamen tiles are deliberately excluded here to prevent 401 errors.
BASEMAP_OPTIONS = {
    "OpenStreetMap": folium.TileLayer('OpenStreetMap', name="OpenStreetMap"),
    "CartoDB Positron": folium.TileLayer('CartoDB Positron', name="CartoDB Positron"),
    "CartoDB Dark Matter": folium.TileLayer('CartoDB Dark Matter', name="CartoDB Dark Matter"),
}


# --- Mock Classification Results (Used for Dashboard Metrics) ---

# Mock classification report data structure
CLASSIFICATION_REPORT = {
    'Bushland/Shrubland': {'precision': 0.96, 'recall': 0.83, 'f1-score': 0.89, 'support': 30},
    'Forest/Riverine': {'precision': 0.95, 'recall': 0.91, 'f1-score': 0.93, 'support': 22},
    'Grassland/Savanna': {'precision': 0.97, 'recall': 1.00, 'f1-score': 0.98, 'support': 148},
    'accuracy': 0.96,
    'macro avg': {'precision': 0.96, 'recall': 0.91, 'f1-score': 0.94, 'support': 200},
    'weighted avg': {'precision': 0.96, 'recall': 0.96, 'f1-score': 0.96, 'support': 200},
}

# The single, concise paragraph generated by Gemini (Model Mock)
AI_INTERPRETATION = """
The GeoAI model demonstrates exceptional performance, achieving 96% overall accuracy. The high F1-score (0.98) for Grassland/Savanna indicates robust detection of the most dominant class. While the recall for Bushland/Shrubland is slightly lower at 83%, the model's performance on Forest/Riverine (93% F1) shows strong capability in differentiating complex, ecologically vital areas, providing a reliable baseline for ecosystem monitoring.
"""

# Default GeoJSON for the sample Area of Interest (AOI)
DEFAULT_AOI_GEOJSON = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [34.9, -1.4],
                        [35.1, -1.4],
                        [35.1, -1.6],
                        [34.9, -1.6],
                        [34.9, -1.4]
                    ]
                ]
            }
        }
    ]
}
